### ISSUE TITLE
use docker-compose v2

### ISSUE THREAD

**Issue by ghetolay** [dcm4che-dockerfiles/dcm4chee-arc-psql#2]
This issue affects all projects (slapd, postgres etc..) not just this one.

Use docker-compose v2, main benefit being named volume.
This means : 

- Use named volume instead of host volume
- Add environnement variable for ldap and db secrets to dcm4chee-arc-psql (because links does not share environnement variable anymore)
    - use ```env_file``` to avoid repetition
    - Rename all ldap and db related environnement variable (from DB_ENV_POSTGRES_DB to POSTGRES_DB for example)
- Clean docker-entrypoint.sh as we don't need to copy files to volumes on first run. (for dcm4chee-arc-psql we may also remove the chown directive, not totally sure)
- *This one has nothing to do with v2 but I think it's good practice:* Use ```expose``` instead of ```ports``` for internal communication (db, ldap, elasticsearch).
 - Use v2 syntax on docker-compose.yml sample.

Using environnement variable for secrets is not optimal but they still didn't found any solid alternative. (you can follow [this issue](https://github.com/docker/docker/issues/13490)).

So docker-compose.yml would look like this (I took the minimal setup as including logstash, elasticsearch... is straightforward) :

db.env
```sh
POSTGRES_DB: pacsdb
POSTGRES_USER: pacs
POSTGRES_PASSWORD: pacs
```
ldap.env
```sh
LDAP_BASE_DN: dc=dcm4che,dc=org
LDAP_ORGANISATION: dcm4che.org
LDAP_ROOTPASS: secret
DEVICE_NAME: dcm4chee-arc
```
docker-compose.yml
```YAML
version: "2"

service:
  slapd:
    image: dcm4che/slapd-dcm4chee:5.2.0
    expose:
      - "389"
    env_file: ./ldap.env
    environment:
      LDAP_CONFIGPASS: secret
      AE_TITLE: DCM4CHEE
      DICOM_HOST: dockerhost
      DICOM_PORT: 11112
      HL7_PORT: 2575
      STORAGE_DIR: /storage/fs1
    volumes:
      - ldap:/var/lib/ldap
      - slapd.d:/etc/ldap/slapd.d
  postgres:
    image: dcm4che/postgres-dcm4chee:5.2.0
    expose:
      - "5432"
    env_file: ./db.env
    volumes:
      - db:/var/lib/postgresql/data
  dcm4chee-arc:
    image: dcm4che/dcm4chee-arc-psql:5.2.0-secure-ui
    ports:
      - "8080:8080"
      - "9990:9990"
      - "11112:11112"
      - "2575:2575"
    env_file:
      - ./db.env
      - ./ldap.env
    links:
      - slapd:ldap
      - postgres:db
    volumes:
      - storage:/storage
      - wildfly:/opt/wildfly/standalone

volumes:
   ldap:
   slapd.d:
   db:
   storage:
   wildfly:
```

Since docker-compose 1.7 we could also add a ```.env```` file containing DICOM and HL7 port to avoid repetition and also a project name to get predictable volume name. But this can be tuning left for final user.
